import os
import json
import logging
import joblib
import pandas as pd
import numpy as np
import sys
from pathlib import Path
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error, mean_absolute_error
from xgboost import XGBRegressor

# Add project root to sys.path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from backend.config import (
    BASE_DIR, RAW_DATA_PATH, MODEL_PATH,
    COL_DATE, COL_STORE_ID, COL_PRODUCT_ID, COL_CATEGORY, COL_REGION,
    COL_INVENTORY_LEVEL, COL_UNITS_SOLD, COL_UNITS_ORDERED, COL_PRICE,
    COL_DISCOUNT, COL_WEATHER, COL_PROMOTION, COL_COMPETITOR_PRICING,
    COL_SEASONALITY, COL_EPIDEMIC, COL_DEMAND
)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def load_data(filepath: str) -> pd.DataFrame:
    """Load the raw CSV data."""
    logger.info(f"Loading data from {filepath}")
    df = pd.read_csv(filepath)
    df[COL_DATE] = pd.to_datetime(df[COL_DATE])
    return df

def feature_engineering(df: pd.DataFrame) -> pd.DataFrame:
    """Create features for the forecasting model."""
    logger.info("Performing feature engineering...")
    df = df.sort_values(by=[COL_STORE_ID, COL_PRODUCT_ID, COL_DATE]).reset_index(drop=True)
    
    # Date features
    df['day_of_week'] = df[COL_DATE].dt.dayofweek
    df['month'] = df[COL_DATE].dt.month
    df['quarter'] = df[COL_DATE].dt.quarter
    df['is_weekend'] = df['day_of_week'].isin([5, 6]).astype(int)
    
    # Lag features per store-product
    group = df.groupby([COL_STORE_ID, COL_PRODUCT_ID])[COL_DEMAND]
    for lag in [1, 7, 14, 28]:
        df[f'demand_lag_{lag}'] = group.shift(lag)
        
    # Rolling stats per store-product (must shift by 1 to avoid data leakage)
    df['demand_rolling_mean_7'] = group.transform(lambda x: x.shift(1).rolling(7).mean())
    df['demand_rolling_std_7'] = group.transform(lambda x: x.shift(1).rolling(7).std())
    df['demand_rolling_mean_28'] = group.transform(lambda x: x.shift(1).rolling(28).mean())
    df['demand_rolling_std_28'] = group.transform(lambda x: x.shift(1).rolling(28).std())
    
    # Price features
    df['price_discount_ratio'] = df[COL_DISCOUNT] / (df[COL_PRICE] + 1e-5)
    df['price_competitor_ratio'] = df[COL_PRICE] / (df[COL_COMPETITOR_PRICING] + 1e-5)
    
    # Binary features
    df[COL_PROMOTION] = df[COL_PROMOTION].map({'Yes': 1, 'No': 0, 1: 1, 0: 0}).fillna(0).astype(int)
    df[COL_EPIDEMIC] = df[COL_EPIDEMIC].map({'Yes': 1, 'No': 0, 1: 1, 0: 0}).fillna(0).astype(int)
    
    # Fill NaN values generated by lags and rolling windows
    df = df.bfill()
    df = df.fillna(0)
    
    return df

def train_model():
    """Train XGBoost model and evaluate."""
    df = load_data(RAW_DATA_PATH)
    df = feature_engineering(df)
    
    # Categorical encoding
    # Weather -> One Hot
    weather_dummies = pd.get_dummies(df[COL_WEATHER], prefix='weather')
    df = pd.concat([df, weather_dummies], axis=1)
    
    # Seasonality -> Ordinal (assuming Winter, Spring, Summer, Fall etc.)
    season_encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
    df['seasonality_encoded'] = season_encoder.fit_transform(df[[COL_SEASONALITY]])
    
    # Define features
    exclude_cols = [COL_DATE, COL_STORE_ID, COL_PRODUCT_ID, COL_CATEGORY, COL_REGION, 
                    COL_UNITS_SOLD, COL_UNITS_ORDERED, COL_INVENTORY_LEVEL, 
                    COL_WEATHER, COL_SEASONALITY, COL_DEMAND]
    
    feature_cols = [c for c in df.columns if c not in exclude_cols]
    
    # Train/Test Split (Time-based: Last 30 days as test)
    max_date = df[COL_DATE].max()
    test_start_date = max_date - pd.Timedelta(days=30)
    
    train_mask = df[COL_DATE] < test_start_date
    test_mask = df[COL_DATE] >= test_start_date
    
    X_train = df.loc[train_mask, feature_cols]
    y_train = df.loc[train_mask, COL_DEMAND]
    X_test = df.loc[test_mask, feature_cols]
    y_test = df.loc[test_mask, COL_DEMAND]
    
    logger.info(f"Train size: {len(X_train)}, Test size: {len(X_test)}")
    
    # Train
    model = XGBRegressor(n_estimators=100, learning_rate=0.1, max_depth=6, random_state=42)
    logger.info("Training XGBoost Regressor...")
    model.fit(X_train, y_train)
    
    # Evaluate
    preds = model.predict(X_test)
    mape = mean_absolute_percentage_error(y_test, preds)
    rmse = mean_squared_error(y_test, preds, squared=False)
    mae = mean_absolute_error(y_test, preds)
    
    metrics = {
        "MAPE": float(mape),
        "RMSE": float(rmse),
        "MAE": float(mae)
    }
    logger.info(f"Evaluation Metrics: {metrics}")
    
    # Save metrics
    artifacts_dir = BASE_DIR / "artifacts"
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    with open(artifacts_dir / "model_metrics.json", "w") as f:
        json.dump(metrics, f, indent=4)
        
    # Save model and feature columns
    model_dir = Path(MODEL_PATH).parent
    model_dir.mkdir(parents=True, exist_ok=True)
    
    joblib.dump({
        "model": model,
        "feature_cols": feature_cols,
        "season_encoder": season_encoder
    }, MODEL_PATH)
    
    logger.info(f"Model saved to {MODEL_PATH}")

if __name__ == "__main__":
    train_model()
